NAV_STATE_MAP = {
    0:  "MANUAL",
    1:  "ALTCTL",
    2:  "POSCTL",
    3:  "AUTO_MISSION",
    4:  "AUTO_LOITER",
    5:  "AUTO_RTL",
    6:  "AUTO_RCRECOVER",
    7:  "AUTO_RTGS",
    8:  "AUTO_LANDENGFAIL",
    9:  "AUTO_LANDGPSFAIL",
    10: "ACRO",
    11: "STABILIZED",
    12: "RATTITUDE",
    13: "AUTO_TAKEOFF",
    14: "AUTO_LAND",
    15: "AUTO_FOLLOW_TARGET",
    16: "AUTO_PRECLAND",
    17: "ORBIT",
    18: "OFFBOARD",
    19: "TERMINATION",
    20: "AUTO_VTOL_TAKEOFF",
    21: "AUTO_VTOL_LAND",
    22: "AUTO_VTOL_TRANSITION_TO_FW",
    23: "AUTO_VTOL_TRANSITION_TO_MC",
    24: "AUTO_VTOL_TRANSITION_TO_FW_FAIL",
    25: "AUTO_VTOL_TRANSITION_TO_MC_FAIL",
}


# Open-dronelog only supports tip and warning types, so we map the PX4 modes to those.
PX4_LOG_LEVEL_MAP = {
    0: "warning", #"EMERGENCY",
    1: "warning", #"ALERT",
    2: "warning", #"CRITICAL",
    3: "warning", #"ERROR",
    4: "tip", #"WARNING",
    5: "tip", #"NOTICE",
    6: "tip", #"INFO",
    7: "tip", #"DEBUG",
}
